# Generated by Django 6.1.1 on 2026-10-06 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('avatar_color', models.CharField(default='#FF5CA8', max_length=20)),
                ('monthly_listeners', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('accent_color', models.CharField(default='#55D6BE', max_length=20)),
                ('bg_class', models.CharField(default='bg-[#55D6BE]', max_length=50)),
                ('rotation', models.CharField(default='rotate-0', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('illustration', models.CharField(default='chill', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mood',
                'verbose_name_plural': 'Moods',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artists', to='music.genre'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_video_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('accent_color', models.CharField(default='#FF5CA8', max_length=20)),
                ('illustration', models.CharField(choices=[('chill', 'Chill'), ('lockin', 'Lock In'), ('mainchar', 'Main Character'), ('unhinged', 'Unhinged'), ('vinyl', 'Vinyl'), ('cassette', 'Cassette'), ('lofi', 'Lo-Fi'), ('retro', 'Retro')], default='vinyl', max_length=50)),
                ('bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('play_count', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.artist')),
                ('genres', models.ManyToManyField(blank=True, related_name='songs', to='music.genre')),
                ('moods', models.ManyToManyField(blank=True, related_name='songs', to='music.mood')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'ordering': ['-play_count', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['title'], name='music_album_title_ddf06b_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', 'title'], name='music_album_artist__3880a1_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['name'], name='music_artis_name_e97718_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['created_at'], name='music_artis_created_4f3166_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='music_song_title_8e56ff_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['youtube_video_id'], name='music_song_youtube_b0f989_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['play_count'], name='music_song_play_co_0d103d_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['created_at'], name='music_song_created_62d7ed_idx'),
        ),
    ]
